version: "3.8"

services:
  postgres:
    image: postgres:14.9-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - 5433:5433
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
  substrate_node:
    image: iso8583-chain
    platform: linux/x86_64
    ports:
      - 9944:9944
    command:
      - --dev
      - --tmp
      - --unsafe-rpc-external
      - --rpc-methods=unsafe
      - --rpc-cors=all
      - -loffchain-worker

  oracle:
    build: ./pcidss
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - 3030:3030
    environment:
      - RUST_LOG=debug
    platform: linux/x86_64
    command:
      - --iso8583-spec=/usr/bin/spec.yaml
      - --database-host=postgres
      - --database-port=5433
      - --ws-url=ws://substrate_node:9944
      - --dev
    links:
      - postgres
      - substrate_node

  interface:
    build: ./interface
    ports:
      - 3002:3002
    environment:
      - GENERATE_SOURCEMAP=false
    depends_on:
      - oracle
      - server

  server:
    build: ./payment-processor
    environment:
      - ORACLE_RPC_URL=ws://oracle:3030
    ports:
      - 3001:3001
    depends_on:
      postgres:
        condition: service_healthy
      oracle:
        condition: service_started

volumes:
  postgres-data:
    driver: local
