version: "3.8"
services:
  postgres:
    image: postgres:14.9-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - 5432:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  oracle:
    image: kingleard/pcidss-oracle:latest
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - 3030:3030
    platform: linux/x86_64
    command:
      - --iso8583-spec=/usr/bin/spec.yaml
      - --database-host=postgres
    links:
      - postgres

volumes:
  postgres-data:
    driver: local
