name: Rust

on:
  push:
    branches: [ "ci-cd" ]
  pull_request:
    branches: [ "ci-cd" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup PostgreSQL
      uses: Harmon758/postgresql-action@v1.0.0
      with:
        # POSTGRES_DB - name for the default database that is created
        postgresql db: postgres
        # POSTGRES_USER - create the specified user with superuser power
        postgresql user: postgres
        # POSTGRES_PASSWORD - superuser password
        postgresql password: postgres
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
